import { ApplianceDeviceType, HVACDeviceType, OBDSystem } from "./types";

// ── Site Constants ──

export const SITE_NAME = "ErrorCodeDB";
export const SITE_URL = "https://errorcodedb.com";
export const SITE_DESCRIPTION =
  "The most comprehensive error code database. Find meanings, causes, and step-by-step fixes for error codes on cars, appliances, HVAC systems, printers, and computers.";

// ── OBD-II ──

export const OBD_SYSTEMS: Record<OBDSystem, { label: string; description: string }> = {
  powertrain: {
    label: "Powertrain (P)",
    description: "Engine, transmission, and emissions system codes",
  },
  body: {
    label: "Body (B)",
    description: "Body electronics, climate control, and seat codes",
  },
  chassis: {
    label: "Chassis (C)",
    description: "ABS, suspension, and steering codes",
  },
  network: {
    label: "Network (U)",
    description: "CAN bus and module communication codes",
  },
};

export const CAR_MAKES = [
  { name: "Toyota", slug: "toyota" },
  { name: "Honda", slug: "honda" },
  { name: "Ford", slug: "ford" },
  { name: "Chevrolet", slug: "chevrolet" },
  { name: "BMW", slug: "bmw" },
  { name: "Mercedes-Benz", slug: "mercedes-benz" },
  { name: "Nissan", slug: "nissan" },
  { name: "Hyundai", slug: "hyundai" },
  { name: "Kia", slug: "kia" },
  { name: "Volkswagen", slug: "volkswagen" },
  { name: "Subaru", slug: "subaru" },
  { name: "Jeep", slug: "jeep" },
  { name: "Ram", slug: "ram" },
  { name: "GMC", slug: "gmc" },
  { name: "Dodge", slug: "dodge" },
  { name: "Mazda", slug: "mazda" },
  { name: "Audi", slug: "audi" },
  { name: "Lexus", slug: "lexus" },
  { name: "Acura", slug: "acura" },
  { name: "Buick", slug: "buick" },
  { name: "Cadillac", slug: "cadillac" },
  { name: "Chrysler", slug: "chrysler" },
  { name: "Infiniti", slug: "infiniti" },
  { name: "Lincoln", slug: "lincoln" },
  { name: "Volvo", slug: "volvo" },
  { name: "Porsche", slug: "porsche" },
  { name: "Land Rover", slug: "land-rover" },
  { name: "Mitsubishi", slug: "mitsubishi" },
  { name: "Tesla", slug: "tesla" },
  { name: "Mini", slug: "mini" },
] as const;

// ── Appliance Brands ──

export const APPLIANCE_BRANDS = [
  // ── USA ──
  { name: "Samsung", slug: "samsung", country: "South Korea" },
  { name: "LG", slug: "lg", country: "South Korea" },
  { name: "Whirlpool", slug: "whirlpool", country: "USA" },
  { name: "Maytag", slug: "maytag", country: "USA" },
  { name: "KitchenAid", slug: "kitchenaid", country: "USA" },
  { name: "GE", slug: "ge", country: "USA" },
  { name: "Frigidaire", slug: "frigidaire", country: "USA" },
  { name: "Kenmore", slug: "kenmore", country: "USA" },
  { name: "Amana", slug: "amana", country: "USA" },
  { name: "Speed Queen", slug: "speed-queen", country: "USA" },
  { name: "Sub-Zero", slug: "sub-zero", country: "USA" },
  { name: "Wolf", slug: "wolf", country: "USA" },
  { name: "Viking", slug: "viking", country: "USA" },
  { name: "Jenn-Air", slug: "jenn-air", country: "USA" },
  { name: "Dacor", slug: "dacor", country: "USA" },
  { name: "Thermador", slug: "thermador", country: "USA" },
  // ── Europe ──
  { name: "Bosch", slug: "bosch", country: "Germany" },
  { name: "Siemens", slug: "siemens", country: "Germany" },
  { name: "Miele", slug: "miele", country: "Germany" },
  { name: "Electrolux", slug: "electrolux", country: "Sweden" },
  { name: "AEG", slug: "aeg", country: "Germany" },
  { name: "Neff", slug: "neff", country: "Germany" },
  { name: "Gaggenau", slug: "gaggenau", country: "Germany" },
  { name: "Liebherr", slug: "liebherr", country: "Switzerland" },
  { name: "Grundig", slug: "grundig", country: "Turkey" },
  { name: "Beko", slug: "beko", country: "Turkey" },
  { name: "Blomberg", slug: "blomberg", country: "Turkey" },
  { name: "Ariston", slug: "ariston", country: "Italy" },
  { name: "Hotpoint", slug: "hotpoint", country: "Italy" },
  { name: "Indesit", slug: "indesit", country: "Italy" },
  { name: "Candy", slug: "candy", country: "Italy" },
  { name: "Hoover", slug: "hoover", country: "Italy" },
  { name: "Zanussi", slug: "zanussi", country: "Italy" },
  { name: "Smeg", slug: "smeg", country: "Italy" },
  { name: "Gorenje", slug: "gorenje", country: "Slovenia" },
  { name: "De'Longhi", slug: "delonghi", country: "Italy" },
  { name: "Asko", slug: "asko", country: "Sweden" },
  { name: "Dyson", slug: "dyson", country: "UK" },
  { name: "Breville", slug: "breville", country: "Australia" },
  { name: "Philips", slug: "philips", country: "Netherlands" },
  // ── Asia ──
  { name: "Panasonic", slug: "panasonic", country: "Japan" },
  { name: "Hitachi", slug: "hitachi", country: "Japan" },
  { name: "Toshiba", slug: "toshiba", country: "Japan" },
  { name: "Sharp", slug: "sharp", country: "Japan" },
  { name: "Daikin", slug: "daikin", country: "Japan" },
  { name: "Mitsubishi Electric", slug: "mitsubishi-electric", country: "Japan" },
  { name: "Rinnai", slug: "rinnai", country: "Japan" },
  { name: "Haier", slug: "haier", country: "China" },
  { name: "Midea", slug: "midea", country: "China" },
  { name: "Hisense", slug: "hisense", country: "China" },
  { name: "TCL", slug: "tcl", country: "China" },
  { name: "Xiaomi", slug: "xiaomi", country: "China" },
  { name: "Galanz", slug: "galanz", country: "China" },
  { name: "Gree", slug: "gree", country: "China" },
  { name: "Chigo", slug: "chigo", country: "China" },
  // ── India ──
  { name: "IFB", slug: "ifb", country: "India" },
  { name: "Godrej", slug: "godrej", country: "India" },
  { name: "Voltas", slug: "voltas", country: "India" },
  { name: "Blue Star", slug: "blue-star", country: "India" },
  // ── New Zealand / Australia ──
  { name: "Fisher & Paykel", slug: "fisher-paykel", country: "New Zealand" },
  // ── Korea ──
  { name: "Cuckoo", slug: "cuckoo", country: "South Korea" },
  { name: "Navien", slug: "navien", country: "South Korea" },
  // ── Specialty / Kitchen ──
  { name: "Ninja", slug: "ninja", country: "USA" },
  { name: "Cuisinart", slug: "cuisinart", country: "USA" },
  { name: "KitchenAid Stand Mixer", slug: "kitchenaid-mixer", country: "USA" },
  { name: "Instant Pot", slug: "instant-pot", country: "Canada" },
  { name: "Vitamix", slug: "vitamix", country: "USA" },
  { name: "Nespresso", slug: "nespresso", country: "Switzerland" },
  { name: "Keurig", slug: "keurig", country: "USA" },
  { name: "iRobot", slug: "irobot", country: "USA" },
  { name: "Roomba", slug: "roomba", country: "USA" },
  { name: "Roborock", slug: "roborock", country: "China" },
  { name: "Ecovacs", slug: "ecovacs", country: "China" },
  { name: "Tineco", slug: "tineco", country: "China" },
  // ── Electronics / Entertainment ──
  { name: "Sony", slug: "sony", country: "Japan" },
  { name: "Vizio", slug: "vizio", country: "USA" },
  { name: "PlayStation", slug: "playstation", country: "Japan" },
  { name: "Xbox", slug: "xbox", country: "USA" },
  { name: "Nintendo", slug: "nintendo", country: "Japan" },
  // ── Networking ──
  { name: "Netgear", slug: "netgear", country: "USA" },
  { name: "TP-Link", slug: "tp-link", country: "China" },
  { name: "Linksys", slug: "linksys", country: "USA" },
  { name: "ASUS Router", slug: "asus-router", country: "Taiwan" },
  // ── Cameras ──
  { name: "Canon Camera", slug: "canon", country: "Japan" },
  { name: "Nikon", slug: "nikon", country: "Japan" },
  { name: "Ring", slug: "ring", country: "USA" },
  { name: "Nest Cam", slug: "nest-cam", country: "USA" },
  // ── Power Tools / Outdoor ──
  { name: "John Deere", slug: "john-deere", country: "USA" },
  { name: "Husqvarna", slug: "husqvarna", country: "Sweden" },
  { name: "Toro", slug: "toro", country: "USA" },
  { name: "Craftsman", slug: "craftsman", country: "USA" },
  { name: "Cub Cadet", slug: "cub-cadet", country: "USA" },
  { name: "Ariens", slug: "ariens", country: "USA" },
  { name: "Stihl", slug: "stihl", country: "Germany" },
  { name: "Ryobi", slug: "ryobi", country: "Japan" },
  { name: "DeWalt", slug: "dewalt", country: "USA" },
  { name: "Makita", slug: "makita", country: "Japan" },
  { name: "Greenworks", slug: "greenworks", country: "USA" },
  { name: "EGO", slug: "ego", country: "USA" },
  { name: "Black & Decker", slug: "black-decker", country: "USA" },
  { name: "Echo", slug: "echo-tools", country: "Japan" },
  { name: "Troy-Bilt", slug: "troy-bilt", country: "USA" },
  { name: "Generac", slug: "generac", country: "USA" },
  // ── Audio / Smart Home ──
  { name: "Sonos", slug: "sonos", country: "USA" },
  { name: "Bose", slug: "bose", country: "USA" },
  { name: "JBL", slug: "jbl", country: "USA" },
  { name: "Yamaha", slug: "yamaha", country: "Japan" },
  { name: "Amazon Alexa", slug: "alexa", country: "USA" },
  { name: "Google Home", slug: "google-home", country: "USA" },
  { name: "Philips Hue", slug: "philips-hue", country: "Netherlands" },
  // ── 3D Printers ──
  { name: "Creality", slug: "creality", country: "China" },
  { name: "Prusa Research", slug: "prusa", country: "Czech Republic" },
  { name: "Bambu Lab", slug: "bambu-lab", country: "China" },
  { name: "Anycubic", slug: "anycubic", country: "China" },
  // ── EV Chargers ──
  { name: "Tesla Wall Connector", slug: "tesla-wall", country: "USA" },
  { name: "ChargePoint", slug: "chargepoint", country: "USA" },
  { name: "JuiceBox / Enel X", slug: "juicebox", country: "USA" },
  // ── Drones ──
  { name: "DJI", slug: "dji", country: "China" },
  { name: "Autel Robotics", slug: "autel", country: "USA" },
  // ── NAS / UPS ──
  { name: "Synology", slug: "synology", country: "Taiwan" },
  { name: "QNAP", slug: "qnap", country: "Taiwan" },
  { name: "APC", slug: "apc", country: "USA" },
  { name: "CyberPower", slug: "cyberpower", country: "USA" },
  // ── Projectors ──
  { name: "Epson Projectors", slug: "epson-projector", country: "Japan" },
  { name: "BenQ", slug: "benq", country: "Taiwan" },
  { name: "Optoma", slug: "optoma", country: "Taiwan" },
  // ── Sewing Machines ──
  { name: "Singer", slug: "singer", country: "USA" },
  { name: "Janome", slug: "janome", country: "Japan" },
  // ── Pool Equipment ──
  { name: "Pentair", slug: "pentair", country: "USA" },
  { name: "Hayward", slug: "hayward", country: "USA" },
  // ── Commercial Trucks / Diesel ──
  { name: "Freightliner", slug: "freightliner", country: "USA" },
  { name: "Kenworth", slug: "kenworth", country: "USA" },
  { name: "Peterbilt", slug: "peterbilt", country: "USA" },
  { name: "Mack Trucks", slug: "mack", country: "USA" },
  { name: "Volvo Trucks", slug: "volvo-truck", country: "Sweden" },
  { name: "Cummins", slug: "cummins", country: "USA" },
  { name: "Detroit Diesel", slug: "detroit-diesel", country: "USA" },
  // ── Micromobility ──
  { name: "Bosch eBike", slug: "bosch-ebike", country: "Germany" },
  { name: "Shimano STEPS", slug: "shimano-steps", country: "Japan" },
  { name: "Brose", slug: "brose", country: "Germany" },
  { name: "Yamaha PW", slug: "yamaha-pw", country: "Japan" },
  { name: "Segway-Ninebot", slug: "segway-ninebot", country: "China" },
  { name: "Xiaomi Scooter", slug: "xiaomi-scooter", country: "China" },
  { name: "Unagi", slug: "unagi", country: "USA" },
  // ── Commercial Kitchen ──
  { name: "True Refrigeration", slug: "true-refrigeration", country: "USA" },
  { name: "Hobart", slug: "hobart", country: "USA" },
  { name: "Vulcan", slug: "vulcan", country: "USA" },
  { name: "Traulsen", slug: "traulsen", country: "USA" },
  { name: "BUNN", slug: "bunn", country: "USA" },
  { name: "Waring", slug: "waring", country: "USA" },
  { name: "Taylor", slug: "taylor", country: "USA" },
  // ── Smart Home / Wearables ──
  { name: "Ecobee", slug: "ecobee", country: "Canada" },
  { name: "Nest Thermostat", slug: "nest-thermostat", country: "USA" },
  { name: "Honeywell Home", slug: "honeywell-home", country: "USA" },
  { name: "Apple Watch", slug: "apple-watch", country: "USA" },
  { name: "Garmin", slug: "garmin", country: "USA" },
  { name: "Fitbit", slug: "fitbit", country: "USA" },
  { name: "Oura", slug: "oura", country: "Finland" },
  { name: "SmartThings", slug: "smartthings", country: "South Korea" },
  { name: "Wyze", slug: "wyze", country: "USA" },
  { name: "Arlo", slug: "arlo", country: "USA" },
  // ── Outdoor Power Tools (new) ──
  { name: "Milwaukee", slug: "milwaukee", country: "USA" },
  { name: "RIDGID", slug: "ridgid", country: "USA" },
  { name: "Honda Power Equipment", slug: "honda-power", country: "Japan" },
  { name: "Kubota", slug: "kubota", country: "Japan" },
  // ── Medical Devices ──
  { name: "Omron", slug: "omron", country: "Japan" },
  { name: "Welch Allyn", slug: "welch-allyn", country: "USA" },
  { name: "Medtronic", slug: "medtronic", country: "USA" },
  { name: "Abbott Libre", slug: "abbott-libre", country: "USA" },
  { name: "Invacare", slug: "invacare", country: "USA" },
  { name: "Pride Mobility", slug: "pride-mobility", country: "USA" },
  { name: "Drive Medical", slug: "drive-medical", country: "USA" },
  { name: "Philips Avent", slug: "philips-avent", country: "Netherlands" },
  // ── RV / Camper ──
  { name: "Dometic", slug: "dometic", country: "Sweden" },
  { name: "Norcold", slug: "norcold", country: "USA" },
  { name: "Atwood", slug: "atwood", country: "USA" },
  { name: "Suburban", slug: "suburban", country: "USA" },
  // ── Marine Electronics ──
  { name: "Garmin Marine", slug: "garmin-marine", country: "USA" },
  { name: "Raymarine", slug: "raymarine", country: "UK" },
  { name: "Simrad", slug: "simrad", country: "Norway" },
  { name: "Minn Kota", slug: "minn-kota", country: "USA" },
  // ── Gaming ──
  { name: "Steam Deck", slug: "steam-deck", country: "USA" },
  // ── Cameras / Photo / Pro Audio ──
  { name: "Sony Camera", slug: "sony-camera", country: "Japan" },
  { name: "Fujifilm", slug: "fujifilm", country: "Japan" },
  { name: "Panasonic Lumix", slug: "panasonic-lumix", country: "Japan" },
  { name: "OM System (Olympus)", slug: "olympus-om", country: "Japan" },
  { name: "GoPro", slug: "gopro", country: "USA" },
  { name: "Insta360", slug: "insta360", country: "China" },
  { name: "Blackmagic Design", slug: "blackmagic", country: "Australia" },
  { name: "Shure", slug: "shure", country: "USA" },
  { name: "Rode", slug: "rode", country: "Australia" },
  { name: "Focusrite", slug: "focusrite", country: "UK" },
  // ── Consumer Networking / Storage ──
  { name: "Eero", slug: "eero", country: "USA" },
  { name: "Google Wifi / Nest", slug: "google-wifi", country: "USA" },
  { name: "Ubiquiti / UniFi", slug: "ubiquiti", country: "USA" },
  { name: "Linksys Velop", slug: "linksys-velop", country: "USA" },
  { name: "Western Digital", slug: "western-digital", country: "USA" },
  { name: "Seagate", slug: "seagate", country: "USA" },
  { name: "SanDisk", slug: "sandisk", country: "USA" },
  { name: "Samsung SSD", slug: "samsung-ssd", country: "South Korea" },
  { name: "Crucial", slug: "crucial", country: "USA" },
  // ── Personal Care ──
  { name: "Dyson Haircare", slug: "dyson-haircare", country: "UK" },
  { name: "Braun", slug: "braun", country: "Germany" },
  { name: "Philips Norelco", slug: "philips-norelco", country: "Netherlands" },
  { name: "Waterpik", slug: "waterpik", country: "USA" },
  { name: "Oral-B", slug: "oral-b", country: "USA" },
  { name: "Philips Sonicare", slug: "sonicare", country: "Netherlands" },
  { name: "Therabody", slug: "theragun", country: "USA" },
  { name: "Hyperice", slug: "hyperice", country: "USA" },
  { name: "NutriBullet", slug: "nutribullet", country: "USA" },
  { name: "Ninja Blender", slug: "ninja-blender", country: "USA" },
  // ── Motorcycles ──
  { name: "Harley-Davidson", slug: "harley-davidson", country: "USA" },
  { name: "Honda Motorcycle", slug: "honda-moto", country: "Japan" },
  { name: "Yamaha Motorcycle", slug: "yamaha-moto", country: "Japan" },
  { name: "Kawasaki", slug: "kawasaki", country: "Japan" },
  { name: "Ducati", slug: "ducati", country: "Italy" },
  { name: "BMW Motorrad", slug: "bmw-moto", country: "Germany" },
  { name: "Indian Motorcycle", slug: "indian", country: "USA" },
  // ── Fitness ──
  { name: "Peloton", slug: "peloton", country: "USA" },
  { name: "NordicTrack", slug: "nordictrack", country: "USA" },
  { name: "Bowflex", slug: "bowflex", country: "USA" },
  { name: "Echelon", slug: "echelon", country: "USA" },
  // ── Medical ──
  { name: "ResMed", slug: "resmed", country: "Australia" },
  { name: "Philips Respironics", slug: "philips-respironics", country: "Netherlands" },
  { name: "Dexcom", slug: "dexcom", country: "USA" },
  // ── Smart Home ──
  { name: "August Home", slug: "august-lock", country: "USA" },
  { name: "Schlage", slug: "schlage", country: "USA" },
  { name: "Yale", slug: "yale", country: "USA" },
  { name: "TP-Link Kasa", slug: "kasa", country: "China" },
  // ── Solar ──
  { name: "Enphase", slug: "enphase", country: "USA" },
  { name: "SolarEdge", slug: "solaredge", country: "Israel" },
  // ── Marine ──
  { name: "Mercury Marine", slug: "mercury-marine", country: "USA" },
  { name: "Yamaha Marine", slug: "yamaha-marine", country: "Japan" },
  // ── Commercial Foodservice ──
  { name: "Manitowoc", slug: "manitowoc", country: "USA" },
  { name: "Hoshizaki", slug: "hoshizaki", country: "Japan" },
  { name: "Scotsman", slug: "scotsman", country: "USA" },
  { name: "Follett", slug: "follett", country: "USA" },
  { name: "TurboChef", slug: "turbochef", country: "USA" },
  { name: "Blodgett", slug: "blodgett", country: "USA" },
  { name: "Lincoln Foodservice", slug: "lincoln-oven", country: "USA" },
  { name: "Frymaster", slug: "frymaster", country: "USA" },
  { name: "Pitco", slug: "pitco", country: "USA" },
  { name: "Delfield", slug: "delfield", country: "USA" },
  // ── Robot Vacuum / Lawn ──
  { name: "Eufy", slug: "eufy", country: "China" },
  { name: "Neato", slug: "neato", country: "USA" },
  { name: "Shark Robot", slug: "shark-robot", country: "USA" },
  { name: "Dreametech", slug: "dreametech", country: "China" },
  { name: "Narwhal", slug: "narwhal", country: "China" },
  { name: "Briggs & Stratton", slug: "briggs-stratton", country: "USA" },
  { name: "Simplicity", slug: "simplicity", country: "USA" },
  { name: "Snapper", slug: "snapper", country: "USA" },
  { name: "Cub Cadet Mower", slug: "cub-cadet-mower", country: "USA" },
  { name: "New Holland", slug: "new-holland", country: "Italy" },
  // ── TV brands ──
  { name: "Sony TV", slug: "sony-tv", country: "Japan" },
  { name: "LG TV", slug: "lg-tv", country: "South Korea" },
  { name: "Samsung TV", slug: "samsung-tv", country: "South Korea" },
  { name: "Vizio TV", slug: "vizio-tv", country: "USA" },
  { name: "TCL TV", slug: "tcl-tv", country: "China" },
  { name: "Hisense TV", slug: "hisense-tv", country: "China" },
  { name: "Philips TV", slug: "philips-tv", country: "Netherlands" },
  { name: "Panasonic TV", slug: "panasonic-tv", country: "Japan" },
  { name: "Roku TV", slug: "roku-tv", country: "USA" },
  { name: "Insignia", slug: "insignia", country: "USA" },
  // ── Audio ──
  { name: "Sonos", slug: "sonos", country: "USA" },
  { name: "Bose", slug: "bose", country: "USA" },
  { name: "JBL", slug: "jbl", country: "USA" },
  { name: "Yamaha Audio", slug: "yamaha-audio", country: "Japan" },
  { name: "Denon", slug: "denon", country: "Japan" },
  { name: "Marantz", slug: "marantz", country: "Japan" },
  { name: "Sennheiser", slug: "sennheiser", country: "Germany" },
  { name: "Bose Headphones", slug: "bose-headphones", country: "USA" },
  { name: "AirPods", slug: "airpods", country: "USA" },
  { name: "Jabra", slug: "jabra", country: "Denmark" },
  // ── Networking / IT ──
  { name: "Cisco", slug: "cisco", country: "USA" },
  { name: "Ubiquiti", slug: "ubiquiti", country: "USA" },
  { name: "eero", slug: "eero", country: "USA" },
  { name: "Google Nest Wifi", slug: "google-nest-wifi", country: "USA" },
  { name: "Synology", slug: "synology", country: "Taiwan" },
  { name: "QNAP", slug: "qnap", country: "Taiwan" },
  { name: "Western Digital", slug: "western-digital", country: "USA" },
  { name: "Seagate", slug: "seagate", country: "USA" },
  { name: "Arris", slug: "arris", country: "USA" },
  { name: "Motorola Modem", slug: "motorola-modem", country: "USA" },
  // ── Smart Home / IoT ──
  { name: "Philips Hue", slug: "philips-hue", country: "Netherlands" },
  { name: "LIFX", slug: "lifx", country: "USA" },
  { name: "Govee", slug: "govee", country: "China" },
  { name: "Wyze", slug: "wyze", country: "USA" },
  { name: "Blink", slug: "blink", country: "USA" },
  { name: "Arlo", slug: "arlo", country: "USA" },
  { name: "myQ", slug: "myq", country: "USA" },
  { name: "Chamberlain", slug: "chamberlain", country: "USA" },
  { name: "LiftMaster", slug: "liftmaster", country: "USA" },
  { name: "Genie", slug: "genie", country: "USA" },
  // ── More European/Premium ──
  { name: "Jenn-Air", slug: "jenn-air", country: "USA" },
  { name: "Dacor", slug: "dacor", country: "USA" },
  { name: "Gaggenau", slug: "gaggenau", country: "Germany" },
  { name: "Fisher & Paykel", slug: "fisher-paykel", country: "New Zealand" },
  { name: "Hotpoint", slug: "hotpoint", country: "UK" },
  { name: "Indesit", slug: "indesit", country: "Italy" },
  { name: "Beko", slug: "beko", country: "Turkey" },
  { name: "Asko", slug: "asko", country: "Sweden" },
  { name: "Zanussi", slug: "zanussi", country: "Italy" },
  // ── Budget / Mid-tier ──
  { name: "Haier", slug: "haier", country: "China" },
  { name: "Hisense Appliance", slug: "hisense-appliance", country: "China" },
  { name: "Midea", slug: "midea", country: "China" },
  { name: "Galanz", slug: "galanz", country: "China" },
  { name: "Danby", slug: "danby", country: "Canada" },
  { name: "Avanti", slug: "avanti", country: "USA" },
  { name: "Magic Chef", slug: "magic-chef", country: "USA" },
  { name: "Euro-Pro", slug: "euro-pro", country: "Canada" },
  { name: "Cuisinart", slug: "cuisinart", country: "USA" },
  { name: "Breville", slug: "breville", country: "Australia" },
  // ── Power Tools ──
  { name: "Hart", slug: "hart", country: "USA" },
  { name: "Bosch Tools", slug: "bosch-tools", country: "Germany" },
  { name: "Festool", slug: "festool", country: "Germany" },
  { name: "Metabo", slug: "metabo", country: "Germany" },
  { name: "Hilti", slug: "hilti", country: "Liechtenstein" },
  { name: "Echo Tools", slug: "echo-tools", country: "Japan" },
  { name: "Kobalt", slug: "kobalt", country: "USA" },
  { name: "Skil", slug: "skil", country: "USA" },
  { name: "Porter-Cable", slug: "porter-cable", country: "USA" },
  { name: "Black & Decker", slug: "black-decker", country: "USA" },
  // ── Motorcycles & Marine ──
  { name: "KTM", slug: "ktm", country: "Austria" },
  { name: "Triumph", slug: "triumph", country: "UK" },
  { name: "Suzuki Moto", slug: "suzuki-moto", country: "Japan" },
  { name: "Kawasaki Moto", slug: "kawasaki-moto", country: "Japan" },
  { name: "Polaris", slug: "polaris", country: "USA" },
  { name: "Indian Motorcycle", slug: "indian-motorcycle", country: "USA" },
  { name: "Aprilia", slug: "aprilia", country: "Italy" },
  { name: "Sea Ray", slug: "sea-ray", country: "USA" },
  { name: "MerCruiser", slug: "mercruiser", country: "USA" },
  { name: "Volvo Penta", slug: "volvo-penta", country: "Sweden" },
  // ── More Commercial ──
  { name: "Rational", slug: "rational", country: "Germany" },
  { name: "Alto-Shaam", slug: "alto-shaam", country: "USA" },
  { name: "Wells", slug: "wells", country: "USA" },
  { name: "Garland", slug: "garland", country: "USA" },
  { name: "Imperial", slug: "imperial", country: "USA" },
  { name: "Southbend", slug: "southbend", country: "USA" },
  { name: "APW Wyott", slug: "apw-wyott", country: "USA" },
  { name: "Winterhalter", slug: "winterhalter", country: "Germany" },
  { name: "Jackson", slug: "jackson", country: "USA" },
  { name: "Champion", slug: "champion", country: "USA" },
  // ── Small kitchen ──
  { name: "Blendtec", slug: "blendtec", country: "USA" },
  { name: "GE Cafe", slug: "ge-cafe", country: "USA" },
  { name: "Cosori", slug: "cosori", country: "USA" },
  { name: "Levoit", slug: "levoit", country: "USA" },
  { name: "Ankarsrum", slug: "ankarsrum", country: "Sweden" },
  { name: "Bonavita", slug: "bonavita", country: "USA" },
  { name: "Technivorm", slug: "technivorm", country: "Netherlands" },
  { name: "Severin", slug: "severin", country: "Germany" },
  { name: "Krups", slug: "krups", country: "France" },
  // ── Diesel & Heavy Truck ──
  { name: "Caterpillar", slug: "caterpillar", country: "USA" },
  { name: "PACCAR", slug: "paccar", country: "USA" },
  { name: "Duramax", slug: "duramax", country: "USA" },
  { name: "Power Stroke", slug: "powerstroke", country: "USA" },
  { name: "Ram Cummins", slug: "ram-cummins", country: "USA" },
  { name: "John Deere Tractor", slug: "john-deere-tractor", country: "USA" },
  { name: "Case IH", slug: "case-ih", country: "USA" },
  { name: "Kubota", slug: "kubota", country: "Japan" },
  { name: "Yanmar", slug: "yanmar", country: "Japan" },
  { name: "Massey Ferguson", slug: "massey-ferguson", country: "USA" },
  // ── Personal Care / Medical ──
  { name: "Dyson Hair", slug: "dyson-hair", country: "UK" },
  { name: "BaByliss", slug: "babyliss", country: "France" },
  { name: "ghd", slug: "ghd", country: "UK" },
  { name: "Braun Shaver", slug: "braun-shaver", country: "Germany" },
  { name: "Philips Shaver", slug: "philips-shaver", country: "Netherlands" },
  { name: "Philips CPAP", slug: "philips-cpap", country: "Netherlands" },
  { name: "Panasonic Shaver", slug: "panasonic-shaver", country: "Japan" },
  { name: "Conair", slug: "conair", country: "USA" },
  { name: "Remington", slug: "remington", country: "USA" },
  { name: "Withings", slug: "withings", country: "France" },
  // ── Streaming + Commercial Refrig ──
  { name: "Roku Streaming", slug: "roku-streaming", country: "USA" },
  { name: "Amazon Fire TV", slug: "amazon-fire-tv", country: "USA" },
  { name: "True Manufacturing", slug: "true-mfg", country: "USA" },
  { name: "Traulsen", slug: "traulsen", country: "USA" },
] as const;

export const APPLIANCE_DEVICE_TYPES: Record<
  ApplianceDeviceType,
  { label: string; labelPlural: string }
> = {
  washer: { label: "Washer", labelPlural: "Washers" },
  dryer: { label: "Dryer", labelPlural: "Dryers" },
  dishwasher: { label: "Dishwasher", labelPlural: "Dishwashers" },
  refrigerator: { label: "Refrigerator", labelPlural: "Refrigerators" },
  microwave: { label: "Microwave", labelPlural: "Microwaves" },
  oven: { label: "Oven", labelPlural: "Ovens" },
  freezer: { label: "Freezer", labelPlural: "Freezers" },
  "air-conditioner": { label: "Air Conditioner", labelPlural: "Air Conditioners" },
  "range-hood": { label: "Range Hood", labelPlural: "Range Hoods" },
  cooktop: { label: "Cooktop", labelPlural: "Cooktops" },
  "wine-cooler": { label: "Wine Cooler", labelPlural: "Wine Coolers" },
  "ice-maker": { label: "Ice Maker", labelPlural: "Ice Makers" },
  "garbage-disposal": { label: "Garbage Disposal", labelPlural: "Garbage Disposals" },
  "water-purifier": { label: "Water Purifier", labelPlural: "Water Purifiers" },
  dehumidifier: { label: "Dehumidifier", labelPlural: "Dehumidifiers" },
  humidifier: { label: "Humidifier", labelPlural: "Humidifiers" },
  "air-purifier": { label: "Air Purifier", labelPlural: "Air Purifiers" },
  vacuum: { label: "Vacuum", labelPlural: "Vacuums" },
  "robot-vacuum": { label: "Robot Vacuum", labelPlural: "Robot Vacuums" },
  "coffee-machine": { label: "Coffee Machine", labelPlural: "Coffee Machines" },
  "espresso-machine": { label: "Espresso Machine", labelPlural: "Espresso Machines" },
  "food-processor": { label: "Food Processor", labelPlural: "Food Processors" },
  blender: { label: "Blender", labelPlural: "Blenders" },
  "pressure-cooker": { label: "Pressure Cooker", labelPlural: "Pressure Cookers" },
  "slow-cooker": { label: "Slow Cooker", labelPlural: "Slow Cookers" },
  "bread-maker": { label: "Bread Maker", labelPlural: "Bread Makers" },
  "rice-cooker": { label: "Rice Cooker", labelPlural: "Rice Cookers" },
  "induction-cooktop": { label: "Induction Cooktop", labelPlural: "Induction Cooktops" },
  "washer-dryer-combo": { label: "Washer-Dryer Combo", labelPlural: "Washer-Dryer Combos" },
  "steam-oven": { label: "Steam Oven", labelPlural: "Steam Ovens" },
  "warming-drawer": { label: "Warming Drawer", labelPlural: "Warming Drawers" },
  tv: { label: "TV", labelPlural: "TVs" },
  "gaming-console": { label: "Gaming Console", labelPlural: "Gaming Consoles" },
  router: { label: "Router", labelPlural: "Routers" },
  camera: { label: "Camera", labelPlural: "Cameras" },
  "security-camera": { label: "Security Camera", labelPlural: "Security Cameras" },
  "sound-bar": { label: "Sound Bar", labelPlural: "Sound Bars" },
  "lawn-mower": { label: "Lawn Mower", labelPlural: "Lawn Mowers" },
  "riding-mower": { label: "Riding Mower", labelPlural: "Riding Mowers" },
  "zero-turn-mower": { label: "Zero-Turn Mower", labelPlural: "Zero-Turn Mowers" },
  chainsaw: { label: "Chainsaw", labelPlural: "Chainsaws" },
  "string-trimmer": { label: "String Trimmer", labelPlural: "String Trimmers" },
  "leaf-blower": { label: "Leaf Blower", labelPlural: "Leaf Blowers" },
  "snow-blower": { label: "Snow Blower", labelPlural: "Snow Blowers" },
  "pressure-washer": { label: "Pressure Washer", labelPlural: "Pressure Washers" },
  generator: { label: "Generator", labelPlural: "Generators" },
  tiller: { label: "Tiller", labelPlural: "Tillers" },
  "robot-mower": { label: "Robot Mower", labelPlural: "Robot Mowers" },
  "power-tool": { label: "Power Tool", labelPlural: "Power Tools" },
  "smart-speaker": { label: "Smart Speaker", labelPlural: "Smart Speakers" },
  "smart-bulb": { label: "Smart Bulb", labelPlural: "Smart Bulbs" },
  "3d-printer": { label: "3D Printer", labelPlural: "3D Printers" },
  "ev-charger": { label: "EV Charger", labelPlural: "EV Chargers" },
  drone: { label: "Drone", labelPlural: "Drones" },
  nas: { label: "NAS", labelPlural: "NAS Devices" },
  ups: { label: "UPS", labelPlural: "UPS Units" },
  projector: { label: "Projector", labelPlural: "Projectors" },
  "sewing-machine": { label: "Sewing Machine", labelPlural: "Sewing Machines" },
  "pool-equipment": { label: "Pool Equipment", labelPlural: "Pool Equipment" },
  motorcycle: { label: "Motorcycle", labelPlural: "Motorcycles" },
  fitness: { label: "Fitness Equipment", labelPlural: "Fitness Equipment" },
  cpap: { label: "CPAP", labelPlural: "CPAP Machines" },
  "glucose-monitor": { label: "Glucose Monitor", labelPlural: "Glucose Monitors" },
  "smart-lock": { label: "Smart Lock", labelPlural: "Smart Locks" },
  "smart-plug": { label: "Smart Plug", labelPlural: "Smart Plugs" },
  "solar-inverter": { label: "Solar Inverter", labelPlural: "Solar Inverters" },
  "marine-engine": { label: "Marine Engine", labelPlural: "Marine Engines" },
  "heavy-truck": { label: "Heavy Truck", labelPlural: "Heavy Trucks" },
  "diesel-engine": { label: "Diesel Engine", labelPlural: "Diesel Engines" },
  "e-bike": { label: "E-Bike", labelPlural: "E-Bikes" },
  "e-scooter": { label: "E-Scooter", labelPlural: "E-Scooters" },
  "battery-pack": { label: "Battery Pack", labelPlural: "Battery Packs" },
  "commercial-refrigeration": { label: "Commercial Refrigeration", labelPlural: "Commercial Refrigeration" },
  "commercial-dishwasher": { label: "Commercial Dishwasher", labelPlural: "Commercial Dishwashers" },
  "commercial-oven": { label: "Commercial Oven", labelPlural: "Commercial Ovens" },
  "commercial-coffee": { label: "Commercial Coffee Machine", labelPlural: "Commercial Coffee Machines" },
  "commercial-blender": { label: "Commercial Blender", labelPlural: "Commercial Blenders" },
  "soft-serve-machine": { label: "Soft-Serve Machine", labelPlural: "Soft-Serve Machines" },
  "commercial-ice-maker": { label: "Commercial Ice Maker", labelPlural: "Commercial Ice Makers" },
  "commercial-fryer": { label: "Commercial Fryer", labelPlural: "Commercial Fryers" },
  "commercial-grill": { label: "Commercial Grill", labelPlural: "Commercial Grills" },
  "small-engine": { label: "Small Engine", labelPlural: "Small Engines" },
  tractor: { label: "Tractor", labelPlural: "Tractors" },
  "smart-thermostat": { label: "Smart Thermostat", labelPlural: "Smart Thermostats" },
  wearable: { label: "Wearable", labelPlural: "Wearables" },
  "smart-hub": { label: "Smart Hub", labelPlural: "Smart Hubs" },
  "blood-pressure-monitor": { label: "Blood Pressure Monitor", labelPlural: "Blood Pressure Monitors" },
  "medical-thermometer": { label: "Medical Thermometer", labelPlural: "Medical Thermometers" },
  "insulin-pump": { label: "Insulin Pump", labelPlural: "Insulin Pumps" },
  "mobility-scooter": { label: "Mobility Scooter", labelPlural: "Mobility Scooters" },
  "baby-monitor": { label: "Baby Monitor", labelPlural: "Baby Monitors" },
  "rv-appliance": { label: "RV Appliance", labelPlural: "RV Appliances" },
  "rv-fridge": { label: "RV Refrigerator", labelPlural: "RV Refrigerators" },
  "rv-water-heater": { label: "RV Water Heater", labelPlural: "RV Water Heaters" },
  "rv-furnace": { label: "RV Furnace", labelPlural: "RV Furnaces" },
  "marine-electronics": { label: "Marine Electronics", labelPlural: "Marine Electronics" },
  "trolling-motor": { label: "Trolling Motor", labelPlural: "Trolling Motors" },
  "action-camera": { label: "Action Camera", labelPlural: "Action Cameras" },
  "cinema-camera": { label: "Cinema Camera", labelPlural: "Cinema Cameras" },
  microphone: { label: "Microphone", labelPlural: "Microphones" },
  "audio-interface": { label: "Audio Interface", labelPlural: "Audio Interfaces" },
  "mesh-router": { label: "Mesh Router", labelPlural: "Mesh Routers" },
  "enterprise-router": { label: "Enterprise Router", labelPlural: "Enterprise Routers" },
  "external-drive": { label: "External Drive", labelPlural: "External Drives" },
  "ssd-drive": { label: "SSD Drive", labelPlural: "SSD Drives" },
  "hair-tool": { label: "Hair Tool", labelPlural: "Hair Tools" },
  "electric-shaver": { label: "Electric Shaver", labelPlural: "Electric Shavers" },
  "water-flosser": { label: "Water Flosser", labelPlural: "Water Flossers" },
  "electric-toothbrush": { label: "Electric Toothbrush", labelPlural: "Electric Toothbrushes" },
  "massage-device": { label: "Massage Device", labelPlural: "Massage Devices" },
  "pool-cleaner": { label: "Pool Cleaner", labelPlural: "Pool Cleaners" },
  "hot-tub": { label: "Hot Tub", labelPlural: "Hot Tubs" },
  "water-softener": { label: "Water Softener", labelPlural: "Water Softeners" },
  "irrigation-controller": { label: "Irrigation Controller", labelPlural: "Irrigation Controllers" },
  "vr-headset": { label: "VR Headset", labelPlural: "VR Headsets" },
  "video-card": { label: "Video Card", labelPlural: "Video Cards" },
  "home-security": { label: "Home Security", labelPlural: "Home Security Systems" },
  "smart-toilet": { label: "Smart Toilet", labelPlural: "Smart Toilets" },
  "smart-faucet": { label: "Smart Faucet", labelPlural: "Smart Faucets" },
  "leak-detector": { label: "Leak Detector", labelPlural: "Leak Detectors" },
  "cable-modem": { label: "Cable Modem", labelPlural: "Cable Modems" },
  "fiber-gateway": { label: "Fiber Gateway", labelPlural: "Fiber Gateways" },
  "av-receiver": { label: "AV Receiver", labelPlural: "AV Receivers" },
  "streaming-device": { label: "Streaming Device", labelPlural: "Streaming Devices" },
  "stand-mixer": { label: "Stand Mixer", labelPlural: "Stand Mixers" },
  "smart-oven": { label: "Smart Oven", labelPlural: "Smart Ovens" },
  laptop: { label: "Laptop", labelPlural: "Laptops" },
  phone: { label: "Phone", labelPlural: "Phones" },
};

// ── HVAC Brands ──

export const HVAC_BRANDS = [
  { name: "Carrier", slug: "carrier" },
  { name: "Lennox", slug: "lennox" },
  { name: "Trane", slug: "trane" },
  { name: "Goodman", slug: "goodman" },
  { name: "Rheem", slug: "rheem" },
  { name: "Bryant", slug: "bryant" },
  { name: "York", slug: "york" },
  { name: "Daikin", slug: "daikin" },
  { name: "Mitsubishi Electric", slug: "mitsubishi" },
  { name: "Fujitsu", slug: "fujitsu" },
  { name: "Honeywell", slug: "honeywell" },
  { name: "Nest", slug: "nest" },
  { name: "Ecobee", slug: "ecobee" },
  { name: "Navien", slug: "navien" },
  { name: "Rinnai", slug: "rinnai" },
  { name: "Weil-McLain", slug: "weil-mclain" },
  { name: "Burnham", slug: "burnham" },
  { name: "A.O. Smith", slug: "ao-smith" },
  { name: "State", slug: "state" },
  { name: "American Standard", slug: "american-standard" },
  { name: "Samsung HVAC", slug: "samsung" },
  { name: "Gree", slug: "gree" },
  { name: "Bryant (extended)", slug: "bryant" },
  { name: "Amana HVAC", slug: "amana-hvac" },
  { name: "Ruud", slug: "ruud" },
  { name: "Heil", slug: "heil" },
  { name: "Tempstar", slug: "tempstar" },
  { name: "Coleman HVAC", slug: "coleman-hvac" },
  { name: "Payne", slug: "payne" },
  { name: "Luxaire", slug: "luxaire" },
  { name: "Coleman", slug: "coleman" },
  { name: "Comfortmaker", slug: "comfortmaker" },
  { name: "KeepRite", slug: "keeprite" },
  { name: "Ducane", slug: "ducane" },
  { name: "Aire-Flo", slug: "aire-flo" },
  { name: "Concord", slug: "concord" },
  { name: "State Water Heater", slug: "state-water" },
  { name: "Buderus", slug: "buderus" },
  { name: "Viessmann", slug: "viessmann" },
  { name: "Lochinvar", slug: "lochinvar" },
  { name: "Triangle Tube", slug: "triangle-tube" },
  { name: "HTP", slug: "htp" },
  { name: "Baxi", slug: "baxi" },
  { name: "Vaillant", slug: "vaillant" },
  { name: "Worcester Bosch", slug: "worcester-bosch" },
] as const;

export const HVAC_DEVICE_TYPES: Record<HVACDeviceType, { label: string; labelPlural: string }> = {
  furnace: { label: "Furnace", labelPlural: "Furnaces" },
  ac: { label: "Air Conditioner", labelPlural: "Air Conditioners" },
  "heat-pump": { label: "Heat Pump", labelPlural: "Heat Pumps" },
  "mini-split": { label: "Mini-Split", labelPlural: "Mini-Splits" },
  "water-heater": { label: "Water Heater", labelPlural: "Water Heaters" },
  thermostat: { label: "Thermostat", labelPlural: "Thermostats" },
  boiler: { label: "Boiler", labelPlural: "Boilers" },
};

// ── Printer Brands ──

export const PRINTER_BRANDS = [
  { name: "HP", slug: "hp" },
  { name: "Canon", slug: "canon" },
  { name: "Epson", slug: "epson" },
  { name: "Brother", slug: "brother" },
  { name: "Xerox", slug: "xerox" },
  { name: "Lexmark", slug: "lexmark" },
  { name: "Kyocera", slug: "kyocera" },
  { name: "Ricoh", slug: "ricoh" },
  { name: "Konica Minolta", slug: "konica-minolta" },
  { name: "OKI", slug: "oki" },
  { name: "Sharp", slug: "sharp-printer" },
  { name: "Toshiba", slug: "toshiba-printer" },
  { name: "Dell", slug: "dell" },
] as const;

// ── Windows Categories ──

export const WINDOWS_CATEGORIES = [
  { name: "Blue Screen (BSOD)", slug: "bsod", description: "Blue Screen of Death stop codes" },
  { name: "Windows Update", slug: "update", description: "Windows Update error codes" },
  { name: "System Errors", slug: "system", description: "System and application errors" },
  { name: "Browser & Network", slug: "browser", description: "Browser and network error codes" },
  { name: "Gaming & Launchers", slug: "gaming", description: "Steam, Epic, Battle.net, Xbox PC app, game launcher errors" },
  { name: "macOS Errors", slug: "macos", description: "macOS kernel panics, iCloud, Time Machine, Safari, SIP errors" },
] as const;

// ── Severity Labels ──

export const SEVERITY_CONFIG = {
  high: { label: "High", color: "bg-severity-high text-white" },
  medium: { label: "Medium", color: "bg-severity-medium text-white" },
  low: { label: "Low", color: "bg-severity-low text-white" },
  info: { label: "Info", color: "bg-severity-info text-white" },
} as const;

export const DIFFICULTY_CONFIG = {
  easy: { label: "Easy", color: "bg-difficulty-easy text-white" },
  intermediate: { label: "Intermediate", color: "bg-difficulty-intermediate text-white" },
  advanced: { label: "Advanced", color: "bg-difficulty-advanced text-white" },
  professional: { label: "Professional", color: "bg-difficulty-professional text-white" },
} as const;

// ── Navigation ──

export const MAIN_NAV_ITEMS = [
  { label: "OBD-II Codes", href: "/obd2" },
  { label: "Appliances", href: "/appliance" },
  { label: "HVAC", href: "/hvac" },
  { label: "Printers", href: "/printer" },
  { label: "Windows", href: "/windows" },
] as const;
